// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
import { createServiceRegistry } from "../grpc-service";
import { registerAllMethods } from "./methods";
// Create models service registry
const modelsService = createServiceRegistry("models");
export const registerMethod = modelsService.registerMethod;
// Export the request handlers
export const handleModelsServiceRequest = modelsService.handleRequest;
export const handleModelsServiceStreamingRequest = modelsService.handleStreamingRequest;
export const isStreamingMethod = modelsService.isStreamingMethod;
// Register all models methods
registerAllMethods();
//# sourceMappingURL=index.js.map