// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
import { createServiceRegistry } from "../grpc-service";
import { registerAllMethods } from "./methods";
// Create account service registry
const accountService = createServiceRegistry("account");
export const registerMethod = accountService.registerMethod;
// Export the request handlers
export const handleAccountServiceRequest = accountService.handleRequest;
export const handleAccountServiceStreamingRequest = accountService.handleStreamingRequest;
export const isStreamingMethod = accountService.isStreamingMethod;
// Register all account methods
registerAllMethods();
//# sourceMappingURL=index.js.map